### ISSUE TITLE
errors when changing wallpaper with variety

### ISSUE THREAD

**Issue by rayvermey** [DenysMb/WCG-WallpaperColorSchemeGenerator#1]
Hi

on my Arch system i use Variety as my wallpaper changer.
When i change to the next wallpaper i get the following errors when running ./wcg from the terminal:

QFile::copy: Empty or null file name
QDBusConnection: error: could not send signal to service "" path "//home/ray/.kde4/share/config/kdeglobals" interface "org.kde.kconfig.notify" member "ConfigChanged": Invalid object path: //home/ray/.kde4/share/config/kdeglobals
QFile::copy: Empty or null file name

The theme does change btw.

Ray

**Comment by DenysMb** [comment]
Hi!

Thank you for open this issue.
This is a upstream bug of the **plasma-apply-colorscheme** command.
This command was [merged in plasma workspace a year ago](https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/630) but it seems that, after one of Plasma update, something broke what seems to be something related to the notification of this command, I guess.

Anyway, this is not a big deal, we can just ignore for now.
